name: Run AndroidTest

on: [push]

env:
  ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk

jobs:
  Run-AndroidTest-Actions:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.7

      - name: Update SDK versions
        run: /Users/runner/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager --update

      - name: Check Emulator version
        run: /Users/runner/Library/Android/sdk/emulator/emulator -version

      - name: Build Debug APK
        run: ./gradlew :app:packageDebug

      - name: Build Debug Android Test APK
        run: ./gradlew :app:packageDebugAndroidTest

      # - name: Run AndroidTest
      #   run: ./gradlew -Dorg.gradle.workers.max=1 allDevicesDebugAndroidTest --info --stacktrace -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=0 -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Run AndroidTest
        run: ./gradlew -Dorg.gradle.workers.max=1 allDevicesDebugAndroidTest --info -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Archive Test Results
        if: always()
        run: zip -r test-results.zip ./app/build

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: test-results.zip
